spring.application.name=book-shop-backend

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/book-shop
spring.datasource.username=postgres
spring.datasource.password=qwerty1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# POSTGRES DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=myVeryStrongSecretKeyForJwtTokenGeneration123456789

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html

# SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration